apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
   config.json: |
     {
        "resourceList": [
             {
                "resourceName": "intel_hostdevice_netdevice",
                "selectors": {
                        "vendors": ["8086"],
                        "devices": ["154c", "10ed", "1889"],
                        "drivers": ["i40evf", "ixgbevf", "iavf"]

                }
           }
        ]
     }